import redis
r = redis.Redis(host='127.0.0.1',port=6379)
r.setnx("name","alxe")
#
# # print(r.get("name"))
# r.hset("info","name","zzzz")
# r.hset("info","age","16")
# print(r.hgetall("info"))
# print(r.hget("info","name"))
# print(r.hget("info","age"))
# print(r.hlen("info"))
# print(r.hvals("info"))
# r.delete("tt")
# r.lpush("tt",11,22,33)
# print(r.lrange("tt",0,-1))
# r.linsert("tt","before",22,44)
# print(r.lrange("tt",0,-1))
# r.lset("tt",1,66)
# print(r.lrange("tt",0,-1))
r.sadd("set1","zhh","zhh","hai","001")
r.sadd("set2","zhh","zhh","ttt","ccc")
print(r.smembers("set1"))
print(r.scard("set1"))
print(r.sdiff("set1","set2"))
