import time,datetime
s = time.time()
d = time.localtime()
print(d)
print("星期》",time.strftime("%a",d))
print("星期》",time.strftime("%A",d))
print("月份》",time.strftime("%B",d))
print("月份》",time.strftime("%b",d))
print("日期》",time.strftime("%Y/%m/%d %H:%M:%S",d))
print("月天》",d.tm_mday)
print("天时》",d.tm_hour)
print("12小时制》",time.strftime("%I",d))
print("年天》",d.tm_yday)
print("月》",d.tm_mon)
print("天分》",d.tm_min)
print("AM,PM》",time.strftime("%p",d))
# print(help(time.strftime))